---
title: "Code for Track 3 - Women's"
output: pdf_document
---

```{r include = FALSE, warning = FALSE}
#read in libraries
library(readr)
library(ggplot2)
library(tidyverse)
library(mosaic)
library(dplyr)
library(tidyr)
library(janitor)
library(ggfortify)
library(forecast)
library(ggthemes)

#read in dataset
results <- read_csv("./results.csv")
```

```{r warning = FALSE}
#filter out specific event
w100M <- results %>% filter(Event == "100M Women")

#transform result (time) to double
w100M <- w100M %>% mutate(Result = as.double(Result))

#manually input toyko 2021 data, webscraping unavailable for olympics.com
w100M <- w100M %>% add_row(Gender = c("W","W","W"),
                           Event = c("100M Women", "100M Women", "100M Women"),
                           Location = c("Tokyo","Tokyo","Tokyo"),
                           Year = c(2020,2020,2020),
                           Medal = c("G","S","B"),
                           Name = c("Elaine THOMPSON","Shelly-Ann FRASER-PRYCE","Shericka JACKSON"),
                           Nationality = c("JAM","JAM","JAM"),
                           Result = c(10.61,10.74,10.76)
                           )

#manually add DUMMY variable for missing years (due to WW2) in order for time analysis to be valid
#1988 olympics also gets a DUMMY variable due to the results being invalid due to wind.
#to to fix this, we took the average of the prior and following year as the input.
w100M <- w100M %>% 
  add_row(Gender = c("W","W","W","W","W","W","W","W","W"),
          Event = c("100M Women", "100M Women", "100M Women","100M Women", "100M Women", "100M Women","100M Women", "100M Women", "100M Women"),
          Location = c("DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY"),
          Year = c(1940,1940,1940,1944,1944,1944,1988,1988,1988),
          Medal = c("G","S","B","G","S","B","G","S","B"),
          Name = c("DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY"),
          Nationality = c("DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY","DUMMY"),
          Result = c(11.70,11.95,12.05,11.70,11.95,12.05,10.90,10.98,11.00)
                           )

#fixing the results of specifics to match olympics.com 
w100M[32,"Result"] <- 12.30
w100M[33,"Result"] <- 12.30
w100M[6,"Medal"] <- "B"
w100M[7,"Medal"] <- "G"
```

```{r}
#pull out gold medal winners
w100M_G <- w100M %>% filter(Medal == "G") %>% arrange(Year)
#pull out silver medal winners
w100M_S <- w100M %>% filter(Medal == "S") %>% arrange(Year)
#pull out bronze medal winners
w100M_B <- w100M %>% filter(Medal == "B") %>% arrange(Year)
```

```{r}
#make individual time series objects for gold, silver, bronze
gts <- ts(w100M_G[8], start = 1928, end = 2020, deltat = 4)
sts <- ts(w100M_S[8], start = 1928, end = 2020, deltat = 4)
bts <- ts(w100M_B[8], start = 1928, end = 2020, deltat = 4)

#prediction graph and summary using Holt's method for exponential time series smoothing for gold medal
g_model <- holt(gts, h = 1, damped = TRUE)
summary(g_model)
autoplot(g_model) + 
  ggtitle("Gold Medal Forecasting using Damped Holt's Method") +
  xlab("Olympic Year") +
  ylab("Time in Seconds") +
  scale_x_continuous(breaks=seq(1928,2024,8)) +
  scale_y_continuous(breaks=seq(10.5,12.4,0.2)) + 
  theme_wsj(base_size = 10, title_family = "sans")

#prediction graph and summary using Holt's method for exponential time series smoothing for silver medal
s_model <- holt(sts, h = 1, damped = TRUE)
summary(s_model)
autoplot(s_model) + 
  ggtitle("Silver Medal Forecasting using Damped Holt's Method") +
  xlab("Olympic Year") +
  ylab("Time in Seconds") +
  scale_x_continuous(breaks=seq(1928,2024,8)) +
  scale_y_continuous(breaks=seq(10.5,12.4,0.2)) + 
  theme_wsj(base_size = 10, title_family = "sans")


#prediction graph and summary using Holt's method for exponential time series smoothing for bronze medal
b_model <- holt(bts, h = 1, damped = TRUE)
summary(b_model)
autoplot(b_model) + 
  ggtitle("Bronze Medal Forecasting using Damped Holt's Method") + 
  xlab("Olympic Year") +
  ylab("Time in Seconds") +
  scale_x_continuous(breaks=seq(1928,2024,8)) +
  scale_y_continuous(breaks=seq(10.5,12.4,0.2)) + 
  theme_wsj(base_size = 10, title_family = "sans")
```

